/*
 * Generate src/mock/champions.ts from the REAL machineloling roster
 * (data/raw/index.json -> champions[role]). Maps the data's role keys to the
 * UI's Role union (ADC -> BOT, SUP -> SUPPORT). Display names are a best-effort
 * de-camel + a small special-case table (mock-quality; cosmetic only).
 *
 * Usage: npm run gen:champions   (from web/)
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const dataDir = path.resolve(here, '..', '..', 'data', 'raw');
const indexPath = path.join(dataDir, 'index.json');
const championsPath = path.join(dataDir, 'champions.json');
const outPath = path.resolve(here, '..', 'src', 'mock', 'champions.ts');

// Most-played role first ("primary"), so role inference can pick it.
const PRIMARY_RANK = 'diamond';

const ROLE_MAP = { TOP: 'TOP', JUNGLE: 'JUNGLE', MID: 'MID', ADC: 'BOT', SUP: 'SUPPORT' };

const SPECIAL = {
  KSante: "K'Sante", Belveth: "Bel'Veth", Chogath: "Cho'Gath", Khazix: "Kha'Zix",
  Kaisa: "Kai'Sa", Velkoz: "Vel'Koz", Reksai: "Rek'Sai", KogMaw: "Kog'Maw",
  Kogmaw: "Kog'Maw", Leblanc: 'LeBlanc', MonkeyKing: 'Wukong', Nunu: 'Nunu & Willump',
  DrMundo: 'Dr. Mundo', JarvanIV: 'Jarvan IV', MissFortune: 'Miss Fortune',
  TahmKench: 'Tahm Kench', TwistedFate: 'Twisted Fate', XinZhao: 'Xin Zhao',
  MasterYi: 'Master Yi', AurelionSol: 'Aurelion Sol', LeeSin: 'Lee Sin',
  Fiddlesticks: 'Fiddlesticks', FiddleSticks: 'Fiddlesticks', RenataGlasc: 'Renata Glasc',
  Zaahen: 'Zaahen', Aurora: 'Aurora', Mel: 'Mel', Ambessa: 'Ambessa', Smolder: 'Smolder',
};

function display(id) {
  if (SPECIAL[id]) return SPECIAL[id];
  return id.replace(/([a-z0-9])([A-Z])/g, '$1 $2');
}

const index = JSON.parse(fs.readFileSync(indexPath, 'utf8'));
const champs = index.champions || {};

// games[id][uiRole] from the chosen rank, used to rank a champ's roles by play.
const games = {};
try {
  const ch = JSON.parse(fs.readFileSync(championsPath, 'utf8'));
  const byRole = ch.by_patch?.[PRIMARY_RANK] || {};
  for (const [dataRole, entries] of Object.entries(byRole)) {
    const role = ROLE_MAP[dataRole];
    if (!role) continue;
    for (const e of entries) {
      (games[e.champion] ||= {})[role] = e.games || 0;
    }
  }
} catch {
  /* champions.json optional; fall back to canonical order */
}

const ROLE_ORDER = ['TOP', 'JUNGLE', 'MID', 'BOT', 'SUPPORT'];

/** id -> Set<Role> */
const map = new Map();
for (const [dataRole, list] of Object.entries(champs)) {
  const role = ROLE_MAP[dataRole];
  if (!role) continue;
  for (const id of list) {
    if (!map.has(id)) map.set(id, new Set());
    map.get(id).add(role);
  }
}

const rows = [...map.entries()]
  .map(([id, roleSet]) => {
    const roles = [...roleSet].sort((a, b) => {
      const ga = games[id]?.[a] ?? 0;
      const gb = games[id]?.[b] ?? 0;
      if (gb !== ga) return gb - ga; // most-played first
      return ROLE_ORDER.indexOf(a) - ROLE_ORDER.indexOf(b);
    });
    return { id, name: display(id), roles };
  })
  .sort((a, b) => a.name.localeCompare(b.name));

const body = rows
  .map((c) => `  { id: ${JSON.stringify(c.id)}, name: ${JSON.stringify(c.name)}, roles: [${c.roles.map((r) => `'${r}'`).join(', ')}] },`)
  .join('\n');

const out = `// AUTO-GENERATED by scripts/gen_champions.mjs from the real machineloling
// roster (data/raw/index.json). Do not edit by hand; run \`npm run gen:champions\`.
import type { Champion } from '../types';

export const CHAMPIONS: Champion[] = [
${body}
];

export const CHAMPIONS_BY_ID: Record<string, Champion> = Object.fromEntries(
  CHAMPIONS.map((c) => [c.id, c]),
);
`;

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, out);
console.log(`wrote ${outPath}: ${rows.length} champions`);
